Home stg
intercode-io/verbose-umbrella pull request #2
Opened 2020-03-13 17:43 UTC by vitalii-toderian

2020-03-13 21:22 UTC, vste23 requested changes

2020-03-13 21:22 UTC, vste23 commented on src/components/FooterComponent/FooterComponent.js
> +            <div className="container-fluid">
no need to use container-fluid and row just to have full width container, div by default already takes full width

2020-03-13 21:22 UTC, vste23 commented on src/components/FooterComponent/FooterComponent.js
> +                <div className="row footer-container footer-dimensions">
no need row here

2020-03-13 21:22 UTC, vste23 commented on src/pages/home/HomeQuestions/QuestionSection.scss
> +    @media (min-width: 360px) {
empty styles

2020-03-15 15:03 UTC, vitalii-toderian commented
![image](https://user-images.githubusercontent.com/61580354/76704006-b98cb280-66de-11ea-9957-dd2fb49f56e3.png)
![image](https://user-images.githubusercontent.com/61580354/76704011-c6110b00-66de-11ea-8dfa-68bcc8dd5663.png)
![image](https://user-images.githubusercontent.com/61580354/76704022-d0330980-66de-11ea-9c47-5642799e072f.png)
desktop empty space at the bottom will be fixed in next commits

2020-03-15 15:07 UTC, vste23 requested changes

2020-03-15 15:07 UTC, vste23 commented on src/pages/home/HomeQuestions/QuestionSection.scss
> +    background-image: url("./questions_bkg_mobile_old.png");
add also
`    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;`

2020-03-15 15:07 UTC, vste23 commented on src/pages/home/HomeQuestions/QuestionSection.scss
> +        background-image: url("./questions_bkg_tablet.png");
add also 
`    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;`

2020-03-15 15:07 UTC, vste23 commented on src/pages/home/HomeQuestions/QuestionSection.scss
> +        background-image: url("./questions_bkg_desktop.png");
add also 
`    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;`

2020-03-16 08:17 UTC, merged